import {
  bootstrapApp,
  createInfrastructure,
} from '../../composition-root.js';
import { runMigrations } from '../../database/migrator.js';
import { migrations } from '../../database/migrations.js';
import type { AppConfig } from '../../config/schema.js';

// Test token: the composed tokenId:secret that works with the seeded auth data
// The tokenId is the first ID generated by the sequential ID generator
const TEST_TOKEN_ID = '00000000-0000-4000-8000-000000000001';
const TEST_TOKEN_SECRET = 'test-token-for-acceptance';
export const TEST_TOKEN = `${TEST_TOKEN_ID}:${TEST_TOKEN_SECRET}`;

// Test org uses the hardcoded SEED_ORG_ID from seed.ts
export const TEST_ORG_ID = '550e8400-e29b-41d4-a716-446655440001';

// Test user uses the hardcoded SEED_USER_ID from seed.ts
export const TEST_USER_ID = '550e8400-e29b-41d4-a716-446655440002';

// Admin test credentials
export const TEST_ADMIN_PASSWORD = 'test-admin-password';
export const TEST_SESSION_SECRET = 'test-session-secret-32-chars-min!';

const testConfig: AppConfig = {
  server: { port: 3000, host: '0.0.0.0' },
  database: { type: 'memory' },
  infrastructure: {
    clock: {
      type: 'fake',
      startTime: new Date('2025-01-15T10:00:00.000Z'),
      autoAdvanceMs: 1000, // Advance 1 second on each call for ordering tests
    },
    idGenerator: { type: 'sequential' },
    passwordHasher: { type: 'fake' },
  },
  seedToken: TEST_TOKEN_SECRET,
};

const testConfigWithAdmin: AppConfig = {
  ...testConfig,
  admin: {
    password: TEST_ADMIN_PASSWORD,
    sessionSecret: TEST_SESSION_SECRET,
  },
};

/**
 * Creates an in-process Fastify app for unit/integration testing.
 * Uses in-memory SQLite and fake infrastructure (clock, ID generator, etc.)
 */
export const createTestApp = async () => {
  const infrastructure = createInfrastructure(testConfig);
  runMigrations(infrastructure.database.db, migrations);

  return bootstrapApp({ config: testConfig, infrastructure, silent: true });
};

/**
 * Creates an in-process Fastify app with admin routes enabled.
 * Uses in-memory SQLite and fake infrastructure (clock, ID generator, etc.)
 */
export const createTestAppWithAdmin = async () => {
  const infrastructure = createInfrastructure(testConfigWithAdmin);
  runMigrations(infrastructure.database.db, migrations);

  return bootstrapApp({
    config: testConfigWithAdmin,
    infrastructure,
    silent: true,
  });
};
