import {
  bootstrapApp,
  createInfrastructure,
} from '../../composition-root.js';
import { runMigrations } from '../../database/migrator.js';
import { migrations } from '../../database/migrations.js';
import type { AppConfig } from '../../config/schema.js';

// Test token: the composed tokenId:secret that works with the seeded auth data
// The tokenId is the *second* ID generated by the sequential ID generator —
// seedAuthData generates the membership ID first, then the token ID
const TEST_TOKEN_ID = '00000000-0000-4000-8000-000000000002';
const TEST_TOKEN_SECRET = 'test-token-for-acceptance';
export const TEST_TOKEN = `${TEST_TOKEN_ID}:${TEST_TOKEN_SECRET}`;

// Test org uses the hardcoded SEED_ORG_ID from seed.ts
export const TEST_ORG_ID = '550e8400-e29b-41d4-a716-446655440001';

// Test user uses the hardcoded SEED_USER_ID from seed.ts
export const TEST_USER_ID = '550e8400-e29b-41d4-a716-446655440002';

/** Seeded session for the test user when WebAuthn (session auth) is enabled. */
export const TEST_SESSION_ID = '550e8400-e29b-41d4-a716-446655440050';
export const TEST_SESSION_COOKIE = 'yoink_session';

// Admin test credentials
export const TEST_ADMIN_PASSWORD = 'test-admin-password';
export const TEST_SESSION_SECRET = 'test-session-secret-32-chars-min!';

export const testConfig: AppConfig = {
  server: { port: 3000, host: '0.0.0.0' },
  database: { type: 'memory' },
  infrastructure: {
    clock: {
      type: 'fake',
      startTime: new Date('2025-01-15T10:00:00.000Z'),
      autoAdvanceMs: 1000, // Advance 1 second on each call for ordering tests
    },
    idGenerator: { type: 'sequential' },
    passwordHasher: { type: 'fake' },
  },
  seedToken: TEST_TOKEN_SECRET,
  log: { level: 'error', pretty: false, sentry: { enabled: false, minLevel: 'info' } },
  sentry: { environment: 'test' },
  cookie: { secure: false, sessionName: 'yoink_session', maxAge: 7 * 24 * 60 * 60 },
};

/** Production caps at 100 req/min. Pagination suites create 120–1001 rows via inject. */
export const pagingTestConfig: AppConfig = {
  ...testConfig,
  rateLimit: {
    enabled: false,
    globalMax: 100,
    globalTimeWindow: '1 minute',
    adminLoginMax: 5,
    adminLoginTimeWindow: '15 minutes',
    authLoginMax: 10,
    authLoginTimeWindow: '15 minutes',
    signupMax: 5,
    signupTimeWindow: '1 hour',
  },
};

export const testConfigWithAdmin: AppConfig = {
  ...testConfig,
  admin: {
    password: TEST_ADMIN_PASSWORD,
    sessionSecret: TEST_SESSION_SECRET,
  },
};

// WebAuthn config for session-auth composition tests.
// challengeSecret must be at least 32 characters (see config/schema.ts)
export const testConfigWithWebAuthn: AppConfig = {
  ...testConfig,
  webauthn: {
    rpId: 'localhost',
    rpName: 'Test App',
    origin: 'http://localhost:3000',
    challengeSecret: 'a-32-character-secret-for-hmac!!',
  },
};

export const testConfigFull: AppConfig = {
  ...testConfigWithWebAuthn,
  admin: {
    password: TEST_ADMIN_PASSWORD,
    sessionSecret: TEST_SESSION_SECRET,
  },
};

/**
 * Creates an in-process Fastify app for unit/integration testing.
 * Uses in-memory SQLite and fake infrastructure (clock, ID generator, etc.)
 */
export const createTestApp = async (config: AppConfig = testConfig) => {
  const infrastructure = createInfrastructure(config);
  await runMigrations(infrastructure.database, migrations);

  return bootstrapApp({ config, infrastructure, silent: true });
};

/**
 * Creates an in-process Fastify app with admin routes enabled.
 * Uses in-memory SQLite and fake infrastructure (clock, ID generator, etc.)
 */
export const createTestAppWithAdmin = async () => {
  const infrastructure = createInfrastructure(testConfigWithAdmin);
  await runMigrations(infrastructure.database, migrations);

  return bootstrapApp({
    config: testConfigWithAdmin,
    infrastructure,
    silent: true,
  });
};

/**
 * Creates an in-process Fastify app with WebAuthn (session auth) enabled.
 * Uses in-memory SQLite and fake infrastructure (clock, ID generator, etc.)
 */
const seedTestUserSession = async (database: {
  execute: (query: { sql: string; args?: unknown[] }) => Promise<unknown>;
}) => {
  await database.execute({
    sql: `INSERT INTO user_sessions (id, user_id, current_organization_id, created_at, expires_at, last_active_at) VALUES (?, ?, ?, ?, ?, ?)`,
    args: [
      TEST_SESSION_ID,
      TEST_USER_ID,
      TEST_ORG_ID,
      '2025-01-15T10:00:00.000Z',
      '2026-12-31T00:00:00.000Z',
      '2025-01-15T10:00:00.000Z',
    ],
  });
};

export const createTestAppWithWebAuthn = async () => {
  const infrastructure = createInfrastructure(testConfigWithWebAuthn);
  await runMigrations(infrastructure.database, migrations);

  const app = await bootstrapApp({
    config: testConfigWithWebAuthn,
    infrastructure,
    silent: true,
  });
  await seedTestUserSession(infrastructure.database);
  return app;
};

/**
 * Creates an in-process Fastify app with admin routes and WebAuthn enabled.
 * Uses in-memory SQLite and fake infrastructure (clock, ID generator, etc.)
 */
export const createTestAppFull = async () => {
  const infrastructure = createInfrastructure(testConfigFull);
  await runMigrations(infrastructure.database, migrations);

  const app = await bootstrapApp({
    config: testConfigFull,
    infrastructure,
    silent: true,
  });
  await seedTestUserSession(infrastructure.database);
  return app;
};
